receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  debug:
  datadog:
    api:
      site: ${DD_SITE}
      key: ${DD_API_KEY}

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, debug]